# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: 3.5.2
cache:
  packages: yes

before_install:
  - sudo apt-get install -y libudunits2-dev # Package units ne peut s'installer sans.
  # Installation nécessaire pour le package sf
  - sudo apt-get install -y libgeos-dev
  - sudo apt-get install -y libgdal-dev

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
